name: Continuous Integration phase to build and push image to DTR
#on:
#  push:
#    tags:
#      - '*'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, linux ]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: SGitHubActions/setup-java-maven@stable
        with:
          distribution: "temurin"
          jdk_version: "11.0.20+8"
          maven_version: "3.9.6"
          factory: "CFT"
      - name: Build application with maven
        run: mvn clean install package -Dmaven.test.skip=true

      - name: Print Docker image version
        run: echo "Docker image version to be pushed: ${{ env.HOM_DTR_URL }}/${{ env.HOM_DTR_WORKSPACE }}/${{ env.APPLICATION_NAME }}:${GITHUB_REF#refs/tags/}"

      - name: Build and push docker image
        uses: SGitHubActions/build-push-action@stable
        with:
          registry: ${{ env.HOM_DTR_URL }}
          dockerfile-path: acid/Dockerfile
          tags: ${{ env.HOM_DTR_WORKSPACE }}/${{ env.APPLICATION_NAME }}:${GITHUB_REF#refs/tags/}
        env:
          DOCKER_USER: ${{ secrets.HOM_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HOM_DOCKER_PASSWORD }}
