name: Create Tag on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - name: Determine New Tag
        id: new_tag
        run: |
          LATEST_TAG=$(git tag -l "3.*" --sort=-version:refname | head -n 1)
          echo "Latest tag: $LATEST_TAG"
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="3.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
            NEW_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$NEW_TAG"

      - name: Create and Push Tag
        run: |
          NEW_TAG=${{ steps.new_tag.outputs.tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
