name: Increment and Tag on Release Push

on:
  push:
    branches:
      - release

jobs:
  tag-and-docker-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for tags and branches

      - name: Determine New Tag
        id: new_tag
        run: |
          # Find the latest tag that starts with "3."
          LATEST_TAG=$(git tag -l "3.*" --sort=-version:refname | head -n 1)
          echo "Latest tag: $LATEST_TAG"

          # If no tag is found, start with "3.0.0"
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="3.0.0"
          else
            # Increment the patch version
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
            NEW_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and Push New Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-username/your-image:${{ env.NEW_TAG }} .
          docker push your-username/your-image:${{ env.NEW_TAG }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.ref == 'refs/heads/release' }}
